# Fondere DataFrame

## Fondere DataFrame

Una caratteristica fondamentale dei DataFrame ben formati è che corrispondono a *tabelle normalizzate*.
In particolare ogni cella di un DataFrame corrisponde a ad un singolo valore, non a liste, dizionari o DataFrame.

Di conseguenza i nostri dati potrebbero essere suddivisi in più tabelle (o DataFrame) che sono collegabili sfruttando campi comuni.

I questa lezione utilizzeremo alcuni dati provenienti dal [Prezzario dei Lavori Pubblici della Toscana](http://dati.toscana.it/dataset/prezzario-lavori-pubblici). Iniziamo a leggere la tabella delle gare non terminate.

In [1]:
import pandas as pd

gare_no = pd.read_csv("data/scpgarenonaggnew.csv.bz2", index_col = 'id_gara')
gare_no.head(1)

oggetto_della_gara numero_gara_anac  \
id_gara                                                                       
41762    ID13FAR001/3 procedura negoziata ai sensi art....              "0"   

           settore                             modalita_realizzazione  \
id_gara                                                                 
41762    Ordinario  Contratto di concessione di servizi e/o forniture   

         importo_gara  num_tot_lotti                 rup            cf_rup  \
id_gara                                                                      
41762     23345484.14              1  MANIAGO ANNA MARIA  MNGNMR54L43A456Z   

        codice_fiscale_stazione_appaltante codice_istat_stazione_appaltante  \
id_gara                                                                       
41762                        "02801630308"                      "006030129"   

                               ...                         classifica  \
id_gara                        ...                                      
41762                          ...                                NaN   

        luogo_esecuzione_istat luogo_esecuzione_nuts num_ordine  \
id_gara                                                           
41762                6000000.0                   NaN          1   

                                   tipo_atto_o_documento  \
id_gara                                                    
41762    Provvedimento di gara non aggiudicata o deserta   

                 data_pubblicazione data_provvedimento num_provvedimento  \
id_gara                                                                    
41762    "2015-08-05T22:00:00.000Z"                NaN               NaN   

             data_pubblicazione_scp  \
id_gara                               
41762    "2015-08-05T22:00:00.000Z"   

                                                 url_esito  
id_gara                                                     
41762    https://www.serviziocontrattipubblici.it/SPInA...  

[1 rows x 39 columns]

In [2]:
gare_no.columns

Index(['oggetto_della_gara', 'numero_gara_anac', 'settore',
       'modalita_realizzazione', 'importo_gara', 'num_tot_lotti', 'rup',
       'cf_rup', 'codice_fiscale_stazione_appaltante',
       'codice_istat_stazione_appaltante', 'denominazione_stazione_appaltante',
       'provincia_stazione_appaltante', 'ufficio',
       'la_sa_agisce_per_conto_di_altro_soggetto',
       'soggetto_per_cui_agisce_la_sa', 'id_lotto', 'cig', 'oggetto_lotto',
       'nr_lotto', 'somma_urgenza', 'tipo_appalto', 'tipo_procedura',
       'criterio_aggiudicazione', 'imp_lotto_netto_sicurezza', 'imp_sicurezza',
       'imp_lotto', 'cup', 'cpv', 'categoria_prevalente', 'classifica',
       'luogo_esecuzione_istat', 'luogo_esecuzione_nuts', 'num_ordine',
       'tipo_atto_o_documento', 'data_pubblicazione', 'data_provvedimento',
       'num_provvedimento', 'data_pubblicazione_scp', 'url_esito'],
      dtype='object')

## Tabelle Prezzario

I dati da leggere per la tabella dei bandi sono particolarmente grandi. Per questo motivo dobbiamo utilizzare l'opzione `low_memory=False`, altrimenti pandas non riuscirà a calcolare correttamente il tipo di dati contenuto in alcune colonne.

In [3]:
bandi = pd.read_csv("data/scpbandinew.csv.bz2", low_memory = False)
bandi.head(3)

id_gara                                 oggetto_della_gara  \
0    59433  Recupero dell'immobile di proprietà comunale d...   
1    59434  Realizzazione del collettore fognario e impian...   
2    59435  Ristrutturazione Cimitero nella frazione di Cà...   

  numero_gara_anac settore modalita_realizzazione  importo_gara  \
0              "0"     NaN                    NaN     381544.90   
1              "0"     NaN                    NaN     748862.50   
2              "0"     NaN                    NaN     275241.04   

   num_tot_lotti  rup cf_rup codice_fiscale_stazione_appaltante  \
0              1  NaN    NaN                      "83503450153"   
1              1  NaN    NaN                      "81003550522"   
2              1  NaN    NaN                                NaN   

              ...             imp_sicurezza  imp_lotto  cup         cpv  \
0             ...                  22080.66  381544.90  NaN  "45233100"   
1             ...                   6197.48  748862.50  NaN  "45232400"   
2             ...                  13763.58  275241.04  NaN  "45215400"   

  categoria_prevalente classifica luogo_esecuzione_istat  \
0                  OG3          I                    NaN   
1                  OG6          I                    NaN   
2                  OG1          I                    NaN   

  luogo_esecuzione_nuts                                          url_bando  \
0                   NaN  https://www.serviziocontrattipubblici.it/SPInA...   
1                   NaN  https://www.serviziocontrattipubblici.it/SPInA...   
2                   NaN  https://www.serviziocontrattipubblici.it/SPInA...   

       data_pubblicazione_scp  
0  "2001-06-19T22:00:00.000Z"  
1  "2001-06-19T22:00:00.000Z"  
2  "2001-06-27T22:00:00.000Z"  

[3 rows x 37 columns]

In [4]:
bandi.columns

Index(['id_gara', 'oggetto_della_gara', 'numero_gara_anac', 'settore',
       'modalita_realizzazione', 'importo_gara', 'num_tot_lotti', 'rup',
       'cf_rup', 'codice_fiscale_stazione_appaltante',
       'codice_istat_stazione_appaltante', 'denominazione_stazione_appaltante',
       'provincia_stazione_appaltante', 'ufficio',
       'la_sa_agisce_per_conto_di_altro_soggetto',
       'soggetto_per_cui_agisce_la_sa', 'data_pubblicazione_bando',
       'data_scadenza_bando', 'id_lotto', 'cig', 'oggetto_lotto', 'nr_lotto',
       'somma_urgenza', 'tipo_appalto', 'tipo_procedura',
       'criterio_aggiudicazione', 'imp_lotto_netto_sicurezza', 'imp_sicurezza',
       'imp_lotto', 'cup', 'cpv', 'categoria_prevalente', 'classifica',
       'luogo_esecuzione_istat', 'luogo_esecuzione_nuts', 'url_bando',
       'data_pubblicazione_scp'],
      dtype='object')

## Tabella Esiti

Leggiamo adesso la tabelle degli esiti delle gare.

In [5]:
esiti = pd.read_csv("data/scpesitinew.csv.bz2", low_memory = False)
esiti.head(3)

id_gara                                 oggetto_della_gara  \
0    40607  Affidamento dei servizi di manutenzione evolut...   
1    40608  lavori di Ristrutturazione Edilizia Edificio S...   
2    40609  Servizio di repertimento e collocamento di per...   

  numero_gara_anac    settore  \
0              "0"  Ordinario   
1              "0"  Ordinario   
2              "0"  Ordinario   

                              modalita_realizzazione  importo_gara  \
0  Contratto di concessione di servizi e/o forniture      92739.00   
1                                Contratto d'appalto     626991.12   
2  Contratto di concessione di servizi e/o forniture     250000.00   

   num_tot_lotti               rup            cf_rup  \
0              1   Troccoli Emilia  TRCMLE65S58H703N   
1              1    Marenco  Elvio  MRNLVE76R13A145G   
2              1  Mannari Leonardo  MNNLRD73D04E625N   

  codice_fiscale_stazione_appaltante  \
0                      "97231970589"   
1                      "00335810040"   
2                      "01098200494"   

                         ...                          \
0                        ...                           
1                        ...                           
2                        ...                           

  ribasso_di_aggiudicazione offerta_in_aumento imp_di_aggiudicazione  \
0                       0.0                NaN           92739.00000   
1                       0.0                NaN          568337.26000   
2                       0.0                NaN          250000.00000   

  data_aggiudicazione_definitiva      data_pubblicazione_scp id_gruppo  ruolo  \
0     "2016-03-21T23:00:00.000Z"  "2016-05-22T22:00:00.000Z"       NaN    NaN   
1     "2016-02-16T23:00:00.000Z"  "2016-05-04T22:00:00.000Z"       NaN    NaN   
2     "2016-05-01T22:00:00.000Z"  "2016-05-05T22:00:00.000Z"       NaN    NaN   

                    aggiudicatario cf_aggiudicatario  \
0                       Gesinf srl       01633591001   
1  Impresa Soda Costruzioni S.r.l.       ***********   
2                     GI Group Spa       11629770154   

                                           url_esito  
0  https://www.serviziocontrattipubblici.it/SPInA...  
1  https://www.serviziocontrattipubblici.it/SPInA...  
2  https://www.serviziocontrattipubblici.it/SPInA...  

[3 rows x 46 columns]

In [6]:
esiti.columns

Index(['id_gara', 'oggetto_della_gara', 'numero_gara_anac', 'settore',
       'modalita_realizzazione', 'importo_gara', 'num_tot_lotti', 'rup',
       'cf_rup', 'codice_fiscale_stazione_appaltante',
       'codice_istat_stazione_appaltante', 'denominazione_stazione_appaltante',
       'provincia_stazione_appaltante', 'ufficio',
       'la_sa_agisce_per_conto_di_altro_soggetto',
       'soggetto_per_cui_agisce_la_sa', 'id_lotto', 'cig', 'oggetto_lotto',
       'nr_lotto', 'somma_urgenza', 'tipo_appalto', 'tipo_procedura',
       'criterio_aggiudicazione', 'imp_lotto_netto_sicurezza', 'imp_sicurezza',
       'imp_lotto', 'cup', 'cpv', 'categoria_prevalente', 'classifica',
       'luogo_esecuzione_istat', 'luogo_esecuzione_nuts', 'num_ordine',
       'tipo_atto_o_documento', 'data_pubblicazione_esito',
       'ribasso_di_aggiudicazione', 'offerta_in_aumento',
       'imp_di_aggiudicazione', 'data_aggiudicazione_definitiva',
       'data_pubblicazione_scp', 'id_gruppo', 'ruolo', 'aggiudica

## Fondere DataFrame

Il campo `id_gara` permette di incrociare i dati presenti nei tre DataFrame: l'istruzione per questa operazione è la `merge`.

In [7]:
fusione = pd.merge(bandi, esiti, on = 'id_gara')
fusione.head(3)

id_gara                               oggetto_della_gara_x  \
0    70411  LAVORI COSTRUZIONE DI N. 2 EDIFICI PER COMPLES...   
1    70517  Appalto integrato, di realizzazione lavori, pr...   
2    70517  Appalto integrato, di realizzazione lavori, pr...   

  numero_gara_anac_x settore_x            modalita_realizzazione_x  \
0                "0"  Speciale  Contratto di concessione di lavori   
1                "0"  Speciale  Contratto di concessione di lavori   
2                "0"  Speciale  Contratto di concessione di lavori   

   importo_gara_x  num_tot_lotti_x              rup_x          cf_rup_x  \
0      2060000.00                1  Anaclerio Gustavo  NCLGTV63C07F839Z   
1     13457469.56                1  AVAGLIANO CARMINE  VGLCMN56D14C361A   
2     13457469.56                1  AVAGLIANO CARMINE  VGLCMN56D14C361A   

  codice_fiscale_stazione_appaltante_x  \
0                        "02573290422"   
1                        "03070190651"   
2                        "03070190651"   

                         ...                          \
0                        ...                           
1                        ...                           
2                        ...                           

  ribasso_di_aggiudicazione offerta_in_aumento imp_di_aggiudicazione  \
0                    15.423                NaN         1768351.07000   
1                    20.498                NaN        10806489.05000   
2                    20.498                NaN        10806489.05000   

  data_aggiudicazione_definitiva    data_pubblicazione_scp_y id_gruppo  \
0     "2005-07-20T22:00:00.000Z"  "2012-01-08T23:00:00.000Z"       NaN   
1     "2006-06-29T22:00:00.000Z"  "2010-01-11T23:00:00.000Z"       1.0   
2     "2006-06-29T22:00:00.000Z"  "2010-01-11T23:00:00.000Z"       1.0   

      ruolo                         aggiudicatario  cf_aggiudicatario  \
0       NaN                     COGEMA COSTRUZIONI        03444941219   
1  Mandante  ARMAFER DEL DOTT. MICHELE MORELLI SRL        00433180759   
2  Mandante                            GECOPRA SRL        05614550639   

                                           url_esito  
0  https://www.serviziocontrattipubblici.it/SPInA...  
1  https://www.serviziocontrattipubblici.it/SPInA...  
2  https://www.serviziocontrattipubblici.it/SPInA...  

[3 rows x 82 columns]

Notiamo che `bandi` e `esiti` condividono diversi nomi di colonne: dobbiamo vedere quale è l'effetto. Calcoliamo i nomi condivisi da entrambi i DataFrame.

In [14]:
print(set(bandi.columns).intersection(set(esiti.columns)))

{'num_tot_lotti', 'tipo_appalto', 'settore', 'id_lotto', 'somma_urgenza', 'importo_gara', 'tipo_procedura', 'data_pubblicazione_scp', 'luogo_esecuzione_nuts', 'ufficio', 'cig', 'criterio_aggiudicazione', 'codice_fiscale_stazione_appaltante', 'cpv', 'la_sa_agisce_per_conto_di_altro_soggetto', 'cup', 'soggetto_per_cui_agisce_la_sa', 'nr_lotto', 'luogo_esecuzione_istat', 'oggetto_lotto', 'numero_gara_anac', 'classifica', 'provincia_stazione_appaltante', 'cf_rup', 'imp_sicurezza', 'categoria_prevalente', 'id_gara', 'rup', 'modalita_realizzazione', 'codice_istat_stazione_appaltante', 'imp_lotto', 'denominazione_stazione_appaltante', 'imp_lotto_netto_sicurezza', 'oggetto_della_gara'}


## Risultato della fusione: colonne

Analizziamo i nomi delle colonne del nuovo DataFrame `fusione`.

In [15]:
fusione.columns

Index(['id_gara', 'oggetto_della_gara_x', 'numero_gara_anac_x', 'settore_x',
       'modalita_realizzazione_x', 'importo_gara_x', 'num_tot_lotti_x',
       'rup_x', 'cf_rup_x', 'codice_fiscale_stazione_appaltante_x',
       'codice_istat_stazione_appaltante_x',
       'denominazione_stazione_appaltante_x',
       'provincia_stazione_appaltante_x', 'ufficio_x',
       'la_sa_agisce_per_conto_di_altro_soggetto_x',
       'soggetto_per_cui_agisce_la_sa_x', 'data_pubblicazione_bando',
       'data_scadenza_bando', 'id_lotto_x', 'cig_x', 'oggetto_lotto_x',
       'nr_lotto_x', 'somma_urgenza_x', 'tipo_appalto_x', 'tipo_procedura_x',
       'criterio_aggiudicazione_x', 'imp_lotto_netto_sicurezza_x',
       'imp_sicurezza_x', 'imp_lotto_x', 'cup_x', 'cpv_x',
       'categoria_prevalente_x', 'classifica_x', 'luogo_esecuzione_istat_x',
       'luogo_esecuzione_nuts_x', 'url_bando', 'data_pubblicazione_scp_x',
       'oggetto_della_gara_y', 'numero_gara_anac_y', 'settore_y',
       'modalita_rea

Siccome sia `bandi` che `esiti` hanno una colonna `num_tot_lotti`, nel DataFrame `fusione` si trovano le colonne `num_tot_lotti_x` (che si riferisce a `num_tot_lotti` di `bandi`) e `num_tot_lotti_y` (che si riferisce a `num_tot_lotti` di `esiti`).

## Risultato della fusione: righe

Ogni riga del DataFrame `fusione` consiste di:
*  una riga di `bandi`
*  una riga di `esiti`.

Più precisamente, le righe di `fusione` corrispondono a **tutte** le coppie di righe, una di `bandi` e una di `esiti` che condividono lo stesso valore della colonna `id_gara`.

Andiamo ad analizzare alcune righe di `fusione`, partendo da quelle con `id_gara` uguale a 70411.

In [66]:
len(bandi[bandi['id_gara'] == 70411])

1

In [67]:
len(esiti[esiti['id_gara'] == 70411])

1

In [68]:
len(fusione[fusione['id_gara'] == 70411])

1

In questo caso, sia `bandi` che  `esiti` hanno una sola riga con `id_gara` 70411: di conseguenza anche `fusione` ha una sola riga con tale `id_gara`.

## Risultato della  fusione: righe (2)

Controlliamo adesso un altro caso: `id_gara` uguale a 70517. Ancora una volta calcoliamo quante righe di `bandi`, `esiti`, e `fusione` abbiamo con questo valore di `id_gara`.

In [20]:
list(bandi['id_gara'] == 70517).count(True)

1

In [21]:
list(esiti['id_gara'] == 70517).count(True)

4

In [22]:
list(fusione['id_gara'] == 70517).count(True)

4

Questo è il caso più frequente: il valore è presente in una sola riga di una tabella, ma in più righe della seconda tabella.

## Risultato della  fusione: righe (3)

Cerchiamo il valore di `id_gara` che è presente nel numero massimo di righe di `bandi`. Questo richiede di utilizzare un raggruppamento e una `idxmax`. Iniziamo con contare, per ogni valore di `id_gara`, quante righe di `bandi` hanno tale valore.

In [23]:
conteggio = bandi.groupby('id_gara').count()['numero_gara_anac']

Controlliamo quante righe dei vari DataFrame hanno 149259 come `id_gara`

In [25]:
list(bandi['id_gara'] == caso).count(True)

2135

In [26]:
list(esiti['id_gara'] == caso).count(True)

1428

In [ ]:
list(fusione['id_gara'] == caso).count(True)

3048780